package com.example.vault.repository;

import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;
import org.springframework.stereotype.Repository;
import com.example.vault.model.AuditLog;

import java.util.List;

/*
 * This interface handles all communication with elasticsearch,
 * By expanding ElasticsearchRepo, spring boot automatically generates the code for saving and searching logs.
 */

@Repository
public interface AuditRepository extends ElasticsearchRepository<AuditLog, String> {
   //custom query: Find all logs generated by a specific user/service
    List<AuditLog> findByActorId(String actorId);

    //custom query: Find all logs a specific action(e.g., "TRANSFER_MONEY")
    List<AuditLog> findByAction(String action);
}
